---
env_vars:
  MONGO_PORT: 3002
  MONGO_IP: 127.0.0.1
  MONGO_USER: admin
  MONGO_PASSWORD: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          66393263323661363937323236323934353937666235343866316661663361366132373633653262
          6262353362343830316162623738343133353432366533370a316462626336363062616663623466
          39323036613835663263383532633434326166636264613234653466656636653463336136666661
          6463366563306562660a656561626137343131653832646264316165326435623735373136626362
          3134
  MAIL_USER: devops591c
  MAIL_PASSWORD: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30653338313438373938383537373762616161306661623938623763663135356132363562313839
          3335373463356666346532383864393266383138303935340a633366363061643231356565333961
          32353837353263353438306365346663616265303433303230396139356664616362383566313939
          3933363262303238350a336133666465663037366236303262623934623062653637313062303433
          3962
  MAIL_SMTP: "smtp.gmail.com"
...
